### ISSUE TITLE
add Navbar

### ISSUE THREAD

**Issue by EricNavar** [ufssd/SSDWebsiteV2#1]
Create a navbar
- add SSD logo on the left hand side
- add 3 buttons centered for Home, Events, and Contact, leading to "/", "/events", and "contact", respectively

**Comment by alago1** [comment]
After #13:
- add SSD logo on the left hand side (currently has a placeholder)
- ~add 3 buttons centered for Home, Events, and Contact, leading to "/", "/events", and "contact", respectively~

**Comment by alago1** [comment]
Completed after #17
