### ISSUE TITLE
add what we do section

### ISSUE THREAD

**Issue by EricNavar** [ufssd/SSDWebsiteV2#5]
- In the home page, add a section titled "What we do".
- On the right, include a photo (it can be a placeholder for now)
- On the left, include the following text: "The Society of Software Developers is focused on helping members learn the principles of software design and apply them to real-world applications. We are more academic in nature than other organizations and work to create a community where students can ask for feedback and assistance for the projects. The concepts discussed and used help with building complex software systems and better prepare members for team projects, internships, and careers in software development."

**Comment by alago1** [comment]
After 07e9efc87ff3aa4030fce65e3be3e8da6894fae1 :
- ~~In the home page, add a section titled "What we do".~~
- On the right, include a photo (currently a placeholder)
- ~~On the left, include the following text: "The Society of Software Developers is focused on helping members learn the principles of software design and apply them to real-world applications. We are more academic in nature than other organizations and work to create a community where students can ask for feedback and assistance for the projects. The concepts discussed and used help with building complex software systems and better prepare members for team projects, internships, and careers in software development."~~

**Comment by alago1** [comment]
Completed after #17.
