### ISSUE TITLE
Add a contact page

### ISSUE THREAD

**Issue by EricNavar** [ufssd/SSDWebsiteV2#6]
- On the left hand side of the contact page, include a photo of Ranger the communications officer and the email ufssd.org@gmail.com.
   - Add a description such as "Leave an email and our Communications Officer Ranger should get in touch"
- On the right hand side include a photo of Varun and his email vpuri@ufl.edu
   - Add a description

**Comment by alago1** [comment]
A few changes on the ui (some still currently in debate) but the contact page has been successfully implemented as of #21
